### ISSUE TITLE
LogManagerService: NullPointerException

### ISSUE THREAD

**Issue by adomigar** [aws-greengrass/aws-greengrass-log-manager#197]
**Describe the bug**
Error "java.lang.NullPointerException: Name is null" when deploying component.

Greengrass.log:

`
[ERROR] (pool-2-thread-52) com.aws.greengrass.logmanager.LogManagerService: service-errored. {serviceName=aws.greengrass.LogManager, currentState=RUNNING}
java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Enum.java:238)
	at org.slf4j.event.Level.valueOf(Level.java:14)
	at com.aws.greengrass.logmanager.CloudWatchAttemptLogsProcessor.checkAndAddNewLogEvent(CloudWatchAttemptLogsProcessor.java:341)
	at com.aws.greengrass.logmanager.CloudWatchAttemptLogsProcessor.processLogLine(CloudWatchAttemptLogsProcessor.java:246)
	at com.aws.greengrass.logmanager.CloudWatchAttemptLogsProcessor.processLogFiles(CloudWatchAttemptLogsProcessor.java:162)
	at com.aws.greengrass.logmanager.LogManagerService.lambda$processLogsAndUpload$23(LogManagerService.java:742)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.aws.greengrass.logmanager.LogManagerService.processLogsAndUpload(LogManagerService.java:741)
	at com.aws.greengrass.logmanager.LogManagerService.startup(LogManagerService.java:766)
	at com.aws.greengrass.lifecyclemanager.Lifecycle.lambda$handleStateTransitionStartingToRunningAsync$9(Lifecycle.java:591)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

**To Reproduce**
The component configuration is: 

******************
{
"reset": [],
  "merge": {
    "logsUploaderConfiguration": {
      "systemLogsConfiguration": {
        "uploadToCloudWatch": true,
        "deleteLogFileAfterCloudUpload": true
      },
      "componentLogsConfigurationMap": {
        "com.cloudwatch.DoorMonitoring": {
          "logFileDirectoryPath": "/greengrass/v2/logs/",
          "logFileRegex": "com.cloudwatch.DoorMonitoring\\w*.log",
          "deleteLogFileAfterCloudUpload": true
        },
        "com.cloudwatch.NetworkReport": {
          "logFileDirectoryPath": "/greengrass/v2/logs/",
          "logFileRegex": "com.cloudwatch.NetworkReport\\w*.log",
          "deleteLogFileAfterCloudUpload": true
        },
        "com.cloudwatch.SystemReport": {
          "logFileDirectoryPath": "/greengrass/v2/logs/",
          "logFileRegex": "com.cloudwatch.SystemReport\\w*.log",
          "deleteLogFileAfterCloudUpload": true
        },
        "com.cleanLogsGarbage": {
          "logFileDirectoryPath": "/greengrass/v2/logs/",
          "logFileRegex": "com.cleanLogsGarbage\\w*.log",
          "deleteLogFileAfterCloudUpload": true
        },
        "com.cloudwatch.ControllerCharger": {
          "logFileDirectoryPath": "/greengrass/v2/logs/",
          "logFileRegex": "com.cloudwatch.ControllerCharger\\w*.log",
          "deleteLogFileAfterCloudUpload": true
        }
      }
    }
  }
}
***************

**Environment**
 - OS: Ubuntu 20.04
 - JDK version:
 - Nucleus version: 2.9.1
 - Log Manager version: 2.3.1

**Comment by MikeDombo** [comment]
This error means that log manger was able to parse a log line, but that the log level (INFO/WARN) was null. This doesn't make sense if the logs are coming from Greengrass.

Are you uploading any logs that you are writing, rather than Greengrass writing it from your component's standard out and standard error?

**Comment by adomigar** [comment]
Thank you very much for your quick response. Adding the setting `"reset":[""]` solves it. I will still check the logs sent by the custom components.

Best regards
