### ISSUE TITLE
logManager: Error while deploying

### ISSUE THREAD

**Issue by JoseOrtega17** [aws-greengrass/aws-greengrass-log-manager#213]
**Describe the bug**
Error while deploying logManager 

**To Reproduce**
Running a new deployment

**Expected behavior**
Deployment success

**Actual behavior**
• DEPLOYMENT_FAILURE
• COMPONENT_UPDATE_ERROR
• COMPONENT_BROKEN

**Environment**
 - OS: Docker container jetson nano Jetpack 32.1
 - JDK version:
```
 openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.19+7-post-Ubuntu-0ubuntu118.04.1, mixed mode)
```
 - Nucleus version: 2.11.2
 - Log Manager version: 2.3.5

**Additional context**
Error when checking GG log:
```

2023-10-25T18:42:54.277Z [ERROR] (pool-2-thread-33) com.aws.greengrass.logmanager.LogManagerService: service-errored. {serviceName=aws.greengrass.LogManager, currentState=RUNNING}
java.lang.NullPointerException: Name is null
	at java.base/java.lang.Enum.valueOf(Enum.java:238)
	at org.slf4j.event.Level.valueOf(Level.java:14)
	at com.aws.greengrass.logmanager.CloudWatchAttemptLogsProcessor.checkAndAddNewLogEvent(CloudWatchAttemptLogsProcessor.java:350)
	at com.aws.greengrass.logmanager.CloudWatchAttemptLogsProcessor.processLogLine(CloudWatchAttemptLogsProcessor.java:251)
	at com.aws.greengrass.logmanager.CloudWatchAttemptLogsProcessor.processLogFiles(CloudWatchAttemptLogsProcessor.java:181)
	at com.aws.greengrass.logmanager.LogManagerService.lambda$processLogsAndUpload$22(LogManagerService.java:769)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.aws.greengrass.logmanager.LogManagerService.processLogsAndUpload(LogManagerService.java:768)
	at com.aws.greengrass.logmanager.LogManagerService.startup(LogManagerService.java:797)
	at com.aws.greengrass.lifecyclemanager.Lifecycle.lambda$handleStateTransitionStartingToRunningAsync$9(Lifecycle.java:591)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by MikeDombo** [comment]
Hello @JoseOrtega17,

Can you please provide the log line that it is trying to upload? Greengrass parsed the log as a Greengrass style log message which must have a valid `level` field in the JSON. Are you writing your own log message in a JSON format?

**Comment by JoseOrtega17** [comment]
Hi @MikeDombo not using a custom log message. How can I check which line is trying to upload? I will try setting level to: INFO to see if it fixes it.
Current config:

```
deprecatedVersionSupport: 'false'
      logsUploaderConfiguration:
        componentLogsConfigurationMap:
          com.org.test:
            diskSpaceLimit: '10'
            diskSpaceLimitUnit: MB
            minimumLogLevel: INFO              
          greengrass:
            diskSpaceLimit: '10'
            diskSpaceLimitUnit: MB
            minimumLogLevel: INFO
          syslog:
            diskSpaceLimit: '50'
            diskSpaceLimitUnit: MB
            logFileDirectoryPath: /var/log
            logFileRegex: syslog\w*
        systemLogsConfiguration:
          deleteLogFileAfterCloudUpload: 'false'
          diskSpaceLimit: '10'
          diskSpaceLimitUnit: MB
          minimumLogLevel: INFO
          uploadToCloudWatch: 'true'
      periodicUploadIntervalSec: '300'
```

**Comment by MikeDombo** [comment]
Hi, can you please remove the syslog upload configuration by doing a configuration update in the deployment with `RESET: [""]` and then merge the configuration that you just posted, but without the `syslog` key.

It seems likely that your syslog entries are being parsed as a Greengrass JSON log which is not valid. Greengrass Log Manager does not officially support syslog uploading; we've never tested that.

**Comment by JoseOrtega17** [comment]
Nice that was the problem, that fixed the issue:

```
Component Name: aws.greengrass.LogManager
    Version: 2.3.6
    State: RUNNING
    Configuration: {"deprecatedVersionSupport":"false","logsUploaderConfiguration":{"componentLogsConfigurationMap":{"com.murine.dax":{"diskSpaceLimit":"10","diskSpaceLimitUnit":"MB","minimumLogLevel":"INFO"},"com.murine.dax_artifacts":{"diskSpaceLimit":"10","diskSpaceLimitUnit":"MB","minimumLogLevel":"INFO"},"com.murine.dax_video":{"diskSpaceLimit":"10","diskSpaceLimitUnit":"MB","minimumLogLevel":"INFO"},"greengrass":{"diskSpaceLimit":"10","diskSpaceLimitUnit":"MB","minimumLogLevel":"INFO"}},"systemLogsConfiguration":{"deleteLogFileAfterCloudUpload":"false","diskSpaceLimit":"10","diskSpaceLimitUnit":"MB","minimumLogLevel":"INFO","uploadToCloudWatch":"false"}},"periodicUploadIntervalSec":"300"}
```

**Comment by MikeDombo** [comment]
Can you please look at your syslogs then and provide an example of one? The log line should start with `{`

**Comment by JoseOrtega17** [comment]
I have these files in _/greengrass/v2/work/aws.greengrass.LogManager/syslog_:
`syslog  syslog.1  syslog.2.gz  syslog.3.gz  syslog.4.gz  syslog.5.gz  syslog.6.gz  syslog.7.gz`
When I cat on syslog a get a bunch of info but nothing starting with {
Only logs like this:
```
EC2MetadataError: failed to get IMDSv2 token and fallback to IMDSv1 is disabled
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: caused by: :
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: #011status code: 0, request id:
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: caused by: RequestError: send request failed
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: caused by: Put "http://169.254.169.254/latest/api/token": dial tcp 169.254.169.254:80: connect: no route to host
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: 2023-10-19 13:23:41 INFO Checking if agent identity type CustomIdentity can be assumed
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: 2023-10-19 13:23:41 ERROR Agent failed to assume any identity
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: 2023-10-19 13:23:41 ERROR failed to find identity, retrying: failed to find agent identity
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: 2023-10-19 13:23:41 INFO Checking if agent identity type OnPrem can be assumed
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: 2023/10/19 13:23:41 Found config file at /etc/amazon/ssm/amazon-ssm-agent.json.
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: Applying config override from /etc/amazon/ssm/amazon-ssm-agent.json.
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: 2023/10/19 13:23:41 processing appconfig overrides
Oct 19 13:23:41 D200-047 amazon-ssm-agent[15080]: 2023-10-19 13:23:41 INFO Checking if agent identity type EC2 can be assumed
Oct 19 13:23:44 D200-047 amazon-ssm-agent[15080]: 2023-10-19 13:23:44 ERROR [EC2Identity] Failed to get instance info from IMDS. Err: failed to get identity instance id. Error: EC2MetadataError: failed to get IMDSv2 token and fallback to IMDSv1 is disabled

```

**Comment by MikeDombo** [comment]
The syslog to look at would be in `/var/log/syslog` which is that path that you configured Greengrass Log Manager to look at

**Comment by JoseOrtega17** [comment]
This is the only info in `/var/log/syslog `
```
cat /var/log/syslog | grep {
Oct 25 12:48:29 D200-047 sh[4542]: + trap echo Received SIGTERM; sigterm_received=1; kill -TERM ${child_pid}; wait ${child_pid}; echo Killed child PID TERM
```

**Comment by MikeDombo** [comment]
OK then, thank you.

As I mentioned, log manager is not equipped right now to upload syslogs so if you avoid that it should all work fine.

With that I would close this issue. Please reopen if you need to.

**Comment by JoseOrtega17** [comment]
Thanks!
