### ISSUE TITLE
[BUG] If not setting logFileRegex we get nullpointer

### ISSUE THREAD

**Issue by fiLLLip** [aws-greengrass/aws-greengrass-log-manager#41]
Non-working config:
```
configuration:
  logsUploaderConfiguration:
    componentLogsConfiguration:
    - componentName: "my.component.name"
      logFileDirectoryPath: "/greengrass/v2/logs/"
      minimumLogLevel: "INFO"
      diskSpaceLimit: "25"
      diskSpaceLimitUnit: "MB"
      deleteLogFileAfterCloudUpload: true
    systemLogsConfiguration:
      deleteLogFileAfterCloudUpload: true
      diskSpaceLimit: "25"
      diskSpaceLimitUnit: "MB"
      minimumLogLevel: "INFO"
      uploadToCloudWatch: true
  periodicUploadIntervalSec: 300
```

Working config:
```
configuration:
  logsUploaderConfiguration:
    componentLogsConfiguration:
    - componentName: "my.component.name"
      logFileDirectoryPath: "/greengrass/v2/logs/"
      minimumLogLevel: "INFO"
      diskSpaceLimit: "25"
      diskSpaceLimitUnit: "MB"
      deleteLogFileAfterCloudUpload: true
      logFileRegex: "my.component.name\\w*.log"
    systemLogsConfiguration:
      deleteLogFileAfterCloudUpload: true
      diskSpaceLimit: "25"
      diskSpaceLimitUnit: "MB"
      minimumLogLevel: "INFO"
      uploadToCloudWatch: true
  periodicUploadIntervalSec: 300
```
Error:
```
2021-01-07T13:09:27.352Z [ERROR] (pool-2-thread-24) com.aws.greengrass.logmanager.LogManagerService: service-errored. {serviceName=aws.greengrass.LogManager, currentState=RUNNING}
java.lang.NullPointerException
        at com.aws.greengrass.logmanager.LogManagerService.processLogsAndUpload(LogManagerService.java:494)
        at com.aws.greengrass.logmanager.LogManagerService.startup(LogManagerService.java:555)
        at com.aws.greengrass.lifecyclemanager.Lifecycle.lambda$handleStateTransitionStartingToRunningAsync$9(Lifecycle.java:531)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Referenced line: https://github.com/aws-greengrass/aws-greengrass-log-manager/blob/14c9c769f74e0dd934f54522bd75c926fcfe0ce0/src/main/java/com/aws/greengrass/logmanager/LogManagerService.java#L494

Issue: Documentation states logFileRegex to be optional, but clearly it is not. https://docs.aws.amazon.com/greengrass/v2/developerguide/log-manager-component.html#log-manager-component-configuration

**Comment by nikkhilmuthye** [comment]
Hi Filip,

Thanks for reporting this. I have reported the issue with the documentation. Currently, these fields are required. The documentation will be fixed later today.

As for making `logFileDirectoryPath` and `logFileRegex` optional, we have a task to do that. If a user component logs to either stdout/stderr, the logging framework used to log to a file (if specified) will be provided by the Greengrass Nucleus. So that time, we will have logs path and file name regex. But if the user component is using their own logging framework, then the `logFileDirectoryPath` and `logFileRegex` will be required fields in the configuration.
