### ISSUE TITLE
(LogManagerService): InterruptException on Logging Lambda Function Component

### ISSUE THREAD

**Issue by mora0136** [aws-greengrass/aws-greengrass-log-manager#42]
**Describe the bug**
When setting up a Lambda function component to display its logs in cloud watch, a java.lan.InterruptedException error occurs on the greengrass runtime. System Level logs work but component logs fail to upload

**To Reproduce**
aws.greengrass.LogManager Merge Configuration:
```
{
  "logsUploaderConfiguration": {
    "systemLogsConfiguration": {
      "uploadToCloudWatch": true,
      "minimumLogLevel": "INFO",
      "diskSpaceLimit": 25,
      "diskSpaceLimitUnit": "MB",
      "deleteLogFileAfterCloudUpload": true
    },
    "componentLogsConfiguration": {
      "componentName": "ComponentName",
      "minimumLogLevel": "INFO",
      "logFileDirectoryPath": "/greengrass/v2/logs/",
      "logFileRegex": "ComponentName\\w*.log",
      "diskSpaceLimit": 25,
      "diskSpaceLimitUnit": "MB",
      "deleteLogFileAfterCloudUpload": true
    }
  },
  "periodicUploadIntervalSec": 600
}
```

**Expected behavior**
Cloud Watch logs of the lambda component are uploaded to cloud watch logs.

**Actual behavior**
An error is visible in the greengrass.log file.
```
2021-01-20T23:18:24.186Z [ERROR] (pool-2-thread-112) com.aws.greengrass.logmanager.LogManagerService: Log Space management interrupted. Returning.. {serviceName=aws.greengrass.LogManager, c
java.lang.InterruptedException                                                                                                                                                                        
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)                                                       
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)                                                                          
    at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)                                                                                                           
    at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)                                                                                                                
    at sun.nio.fs.AbstractWatchService.take(AbstractWatchService.java:118)                                                                                                                        
    at com.aws.greengrass.logmanager.LogManagerService.startWatchServiceOnLogFilePaths(LogManagerService.java:588)                                                                                
    at com.aws.greengrass.logmanager.LogManagerService.lambda$scheduleSpaceManagementThread$9(LogManagerService.java:278)                                                                         
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                                                                    
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                                                   
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                                            
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                                            
    at java.lang.Thread.run(Thread.java:748)
```

**Environment**
 - OS: Raspbian Stretch
 - JDK version: 1.8.0_275
 - Nucleus version: 2.0.3
 - Log Manager version: 2.0.3

**Comment by nikkhilmuthye** [comment]
Hi Brodie,

Thanks for using Greengrass and reporting the issue. The InterruptedException is an expected error and is harmless. Since the component is watching the logs directory, the exception happens during any shut down or restart of the Log Manager component.

The issue of your lambda component logs not being uploaded is not related to that exception. I see that in the configuration you provided, you mentioned that the lambda component's name is `ComponentName` and that the log file its logging to is `ComponentName\\w*.log`. Can you replace that with the actual name of your lambda component in this config? Also, the component configuration object is a list. So your configuration should look something like this.

```
{
  "logsUploaderConfiguration": {
    "systemLogsConfiguration": {
      "uploadToCloudWatch": true,
      "minimumLogLevel": "INFO",
      "diskSpaceLimit": 25,
      "diskSpaceLimitUnit": "MB",
      "deleteLogFileAfterCloudUpload": true
    },
    "componentLogsConfiguration": [
     {
        "componentName": "<ComponentName>",
        "minimumLogLevel": "INFO",
        "logFileDirectoryPath": "/greengrass/v2/logs/",
        "logFileRegex": "<ComponentName>\\w*.log",
        "diskSpaceLimit": 25,
        "diskSpaceLimitUnit": "MB",
        "deleteLogFileAfterCloudUpload": true
      }
  ]
  },
  "periodicUploadIntervalSec": 600
}
```

**Comment by mora0136** [comment]
Thanks for that advice, I was finally able to get it to work by adding that array to the component logs configuration. Perhaps there could be some type of configuration checking in the console to ensure small errors like this do not cause headaches for others that may miss it.
