### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by msauterDS** [aws-greengrass/aws-greengrass-log-manager#87]
**Describe the bug**
I deployed the LogManager component to our greengrass device together with our custom component, TokenExchangeService and the ShadowManager. At the deployment I got an StackOverflowError:
```
2022-03-04T11:08:31.224Z [ERROR] (pool-2-thread-20) com.aws.greengrass.logmanager.LogManagerService: service-errored. {serviceName=aws.greengrass.LogManager, currentState=RUNNING}
java.lang.StackOverflowError
        at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4937)
        at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4863)
        at java.base/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4306)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4344)
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
        at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4941)
        at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4863)
        at java.base/java.util.regex.Pattern$CharPropertyGreedy.match(Pattern.java:4306)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4344)
.......
2022-03-04T11:08:31.291Z [INFO] (aws.greengrass.LogManager-lifecycle) com.aws.greengrass.logmanager.LogManagerService: service-set-state. {serviceName=aws.greengrass.LogManager, currentState=RUNNING, newState=ERRORED}
2022-03-04T11:08:31.292Z [INFO] (aws.greengrass.LogManager-lifecycle) com.aws.greengrass.logmanager.LogManagerService: service-set-state. {serviceName=aws.greengrass.LogManager, currentState=ERRORED, newState=STOPPING}
2022-03-04T11:08:31.298Z [INFO] (aws.greengrass.LogManager-lifecycle) com.aws.greengrass.logmanager.LogManagerService: service-set-state. {serviceName=aws.greengrass.LogManager, currentState=STOPPING, newState=INSTALLED}
2022-03-04T11:08:31.300Z [INFO] (aws.greengrass.LogManager-lifecycle) com.aws.greengrass.logmanager.LogManagerService: service-set-state. {serviceName=aws.greengrass.LogManager, currentState=INSTALLED, newState=STARTING}
2022-03-04T11:08:31.301Z [INFO] (aws.greengrass.LogManager-lifecycle) com.aws.greengrass.logmanager.LogManagerService: service-set-state. {serviceName=aws.greengrass.LogManager, currentState=STARTING, newState=RUNNING}
```

**To Reproduce**
```
{
  "reset": [],
  "merge": {
    "logsUploaderConfiguration": {
      "systemLogsConfiguration": {
        "uploadToCloudWatch": true,
        "minimumLogLevel": "INFO",
        "diskSpaceLimit": 1,
        "diskSpaceLimitUnit": "MB",
        "deleteLogFileAfterCloudUpload": true
      },
      "componentLogsConfiguration": [
        {
          "componentName": "<MY_COMPONENT_NAME",
          "minimumLogLevel": "INFO",
          "diskSpaceLimit": 1,
          "diskSpaceLimitUnit": "MB",
          "deleteLogFileAfterCloudUpload": true
        }
      ]
    },
    "periodicUploadIntervalSec": 60
  }
}
```
MY_COMPONENT_NAME is de.xxxxxxx.module-e4339dab-9640-4491-8aa0-78dd909b75c8-xxxxxxx20220302-uploadImage

**Expected behavior**
The LogManager is uploading the logs every 60 sec to CloudWatch and deletes the log files after the upload.

**Actual behavior**
No logs are uploaded to CloudWatch

**Environment**
 - OS: Amazon Linux 2 (greengrass docker container)
 - JDK version: 
```
openjdk 11.0.13 2021-10-19 LTS
OpenJDK Runtime Environment Corretto-11.0.13.8.2 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.13.8.2 (build 11.0.13+8-LTS, mixed mode)
```
 - Nucleus version: 2.5.3
 - Log Manager version: Tested with 2.2.2 and 2.2.1

**Comment by MikeDombo** [comment]
Hello @msauterDS,
This issue is known and has been fixed already. We will release the fix soon but you can also consume the fix immediately by building the main branch in this repository and making your own private version of the aws.greengrass.LogManager component with that new artifact.

**Comment by msauterDS** [comment]
Hi @MikeDombo,
thanks for the fast response. 
What do you think is "soon" :) ?

**Comment by MikeDombo** [comment]
It should be within a week

**Comment by msauterDS** [comment]
With the new version 2.2.3 it is working.
Thank you.
