### ISSUE TITLE
LogManager: java.nio.file.NoSuchFileException: /greengrass/v2/logs/greengrass_2022_09_26_22_0.log

### ISSUE THREAD

**Issue by bml1g12** [aws-greengrass/aws-greengrass-log-manager#96]
**Describe the bug**

I am getting a NoSuchFileException a few times a day. As far as I can see the log manager is working fine, but it seems that during it's log rotation it's searching for a file that it cannot find. When I look for this log file with `sudo ls` I can see the file does indeed not exist, so it seems to be a bug whereby it is looking to access a file that no longer exists. 

**To Reproduce**

- Running on a Rasberry Pi 
```
{
  "reset": [],
  "merge": {
    "logsUploaderConfiguration": {
      "systemLogsConfiguration": {
        "uploadToCloudWatch": "true",
        "minimumLogLevel": "INFO",
        "diskSpaceLimit": "100",
        "diskSpaceLimitUnit": "MB",
        "deleteLogFileAfterCloudUpload": "false"
      }
    },
    "periodicUploadIntervalSec": "300"
  }
}
```

**Expected behavior**

Would expect no errors logged during normal operation 

**Actual behavior**
Logs the following:

```
2022-09-27T10:08:38.657+09:00Copy2022-09-27T01:08:38.657Z [WARN] (pool-2-thread-10) com.aws.greengrass.logmanager.LogManagerService: Unchecked error thrown when collecting files to be deleted. {serviceName=aws.greengrass.LogManager, currentState=RUNNING} | 2022-09-27T01:08:38.657Z [WARN] (pool-2-thread-10) com.aws.greengrass.logmanager.LogManagerService: Unchecked error thrown when collecting files to be deleted. {serviceName=aws.greengrass.LogManager, currentState=RUNNING}
-- | --
```

```

2022-09-27T10:08:49.407+09:00Copyjava.nio.file.NoSuchFileException: /greengrass/v2/logs/greengrass_2022_09_26_22_0.log	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)	at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83)	at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103)	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)	at com.aws.greengrass.logmanager.LogManagerService.deleteFilesIfNecessary(LogManagerService.java:746)	at com.aws.greengrass.logmanager.LogManagerService.startWatchServiceOnLogFilePaths(LogManagerService.java:708)	at com.aws.greengrass.logmanager.LogManagerService.lambda$scheduleSpaceManagementThread$9(LogManagerService.java:342)	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)	at java.base/java.lang.Thread.run(Thread.java:829) | java.nio.file.NoSuchFileException: /greengrass/v2/logs/greengrass_2022_09_26_22_0.log at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149) at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) at java.base/java.nio.file.Files.readAttributes(Files.java:1764) at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219) at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276) at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373) at java.base/java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:83) at java.base/java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:103) at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132) at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) at com.aws.greengrass.logmanager.LogManagerService.deleteFilesIfNecessary(LogManagerService.java:746) at com.aws.greengrass.logmanager.LogManagerService.startWatchServiceOnLogFilePaths(LogManagerService.java:708) at com.aws.greengrass.logmanager.LogManagerService.lambda$scheduleSpaceManagementThread$9(LogManagerService.java:342) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829)
-- | --
```

**Environment**
 - OS: Raspbian GNU/Linux 11 (bullseye)
 - JDK version: openjdk 11.0.14 2022-01-18
 - Nucleus version: Greengrass core version: 2.5.6
 - Log Manager version: 2.2.6

**Additional context**

As far as I can see logs are being sent to cloudwatch successfully; but I am unclear if I am losing logs from the files that are erroring here

**Comment by MikeDombo** [comment]
@bml1g12,
Thank you for reporting this. As you noted, we are logging this error, but it is an expected condition which does not impact the functionality of Log Manager.

**Comment by MikeDombo** [comment]
@dgggIoT Let's drop the log level for https://github.com/aws-greengrass/aws-greengrass-log-manager/blob/main/src/main/java/com/aws/greengrass/logmanager/LogManagerService.java#L709-L712 as it isn't really any issue. It does not need to be at WARN. Debug should be fine to use in this case.

**Comment by bml1g12** [comment]
Thanks for this information. If it's expected I'd suggest changing the message itself also to inform the user that the message that it is expected rather than an "Unchecked error" (which sounds unexpected). As @MikeDombo suggested also dropping the log level would be great.

Having this issue creates an obstacle for easily identifying error level events from the logs, as we need to explicitly add filters to remove them otherwise.

**Comment by MikeDombo** [comment]
@bml1g12 thank your for your feedback. I would also suggest looking for `[ERROR]` to identify errors, as this message is already at `[WARN]`, which may or may not be a problem, but quite often it isn't an issue.
